"""app.py — the lab target: a fake marketplace and forum served over Tor.

    python lab/app.py --http 8080 --https 8443

**This is a target, not a product.** It exists so the collectors have a real
Tor v3 hidden service to crawl instead of reading JSON off disk. Every page it
serves says so, in the visible HTML, in a `<meta>` tag, in an `X-Lab-Target`
response header and in robots.txt. Nothing here should ever be mistaken for a
real service, by a person or by a crawler.

It renders `fixtures/` — the same corpus the offline path reads — so a
collected run can be diffed against a fixtures run and any loss of fidelity
shows up as a scoring difference. That diff is the point of the whole exercise.

FIDELITY IS THE WHOLE JOB
-------------------------
The extractor reads `bio + key_blocks + post titles + bodies`. If one character
changes on its way through HTML, the writeprint vocabulary shifts and every
score moves. Measured on this corpus: all 420 text fields are single-line with
no tabs, no carriage returns and no leading or trailing space, and every one
survives `html.escape` → `html.unescape` exactly. So the rule is simply:

  * emit each field inside an element with **no internal indentation**, because
    `get_text()` returns literal whitespace and a pretty-printed template would
    inject some;
  * escape with `html.escape`, which the parser reverses on the way back;
  * put the PGP blocks — the only multi-line text — inside `<pre>`, which
    preserves their newlines, and those newlines feed the crc24 checksum.

PLANTED MISCONFIGURATIONS
-------------------------
Two, both deliberate, both the sort of thing recon is built to notice:

  * `/server-status` returns 200 with a mod_status-style page. On a real hidden
    service this leaks vhosts, client IPs and in-flight request URIs.
  * The HTTPS listener serves a certificate whose SAN names
    `gamma-mirror.hostvault.net` and whose serial is `0F3A9C1D77B54E2A` — both
    already present in `fixtures/clearnet_obs/`, so `recon.correlate` fires
    `tls_serial` at 1.00 and `tls_san` at 0.95 against data collected live.
"""

from __future__ import annotations

import argparse
import html
import json
import sys
import threading
from datetime import datetime, timedelta, timezone
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer
from pathlib import Path
from typing import Optional

ROOT = Path(__file__).resolve().parent.parent
FIXTURES = ROOT / "fixtures"

BANNER = (
    "LAB TARGET — synthetic content generated by scripts/gen_fixtures.py for "
    "Dark Sentinel v2 collector testing. Not a real service. No real vendors, "
    "no real buyers, no real goods."
)

#: Both already appear in fixtures/clearnet_obs/shodan_observations.json, so a
#: live recon run correlates against them.
TLS_SAN = "gamma-mirror.hostvault.net"
TLS_SERIAL = 0x0F3A9C1D77B54E2A


# ─────────────────────────────────────────────────────────────────────────────
# Corpus
# ─────────────────────────────────────────────────────────────────────────────

def _read(path: Path):
    return json.loads(path.read_text(encoding="utf-8"))


class Corpus:
    """The fixture corpus, indexed for serving."""

    def __init__(self) -> None:
        self.sources = {s["name"]: s for s in _read(FIXTURES / "sources.json")}
        self.personas: list[dict] = []
        self.posts: dict[int, list[dict]] = {}
        for name in ("market_alpha", "forum_beta", "market_gamma"):
            self.personas += _read(FIXTURES / name / "personas.json")
            for post in _read(FIXTURES / name / "posts.json"):
                self.posts.setdefault(post["persona_id"], []).append(post)
        # Deterministic order: the collector must see posts in one fixed order
        # or the concatenated text — and therefore the writeprint — shifts.
        for posts in self.posts.values():
            posts.sort(key=lambda p: (p.get("posted_at") or "", p["id"]))

        self.by_handle = {p["handle"]: p for p in self.personas}
        self.key_blocks: dict[int, list[str]] = {}
        for block in _read(FIXTURES / "pgp_blocks.json"):
            self.key_blocks.setdefault(block["persona_id"], []).append(block["armored"])

        self.feedback: dict[int, list[dict]] = {}
        path = FIXTURES / "feedback.json"
        if path.exists():
            for row in _read(path):
                self.feedback.setdefault(row["persona_id"], []).append(row)

    def for_source(self, name: str) -> list[dict]:
        return [p for p in self.personas if p["source"] == name]


# ─────────────────────────────────────────────────────────────────────────────
# Rendering
#
# `f` marks a field the collector reads back. Its text is escaped and placed
# with no surrounding whitespace, so `get_text()` returns the original exactly.
# ─────────────────────────────────────────────────────────────────────────────

def f(field: str, value: Optional[str], tag: str = "div") -> str:
    return f'<{tag} data-f="{field}">{html.escape(value or "")}</{tag}>'


def page(title: str, body: str) -> bytes:
    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="robots" content="noindex, nofollow">
<meta name="x-lab-target" content="synthetic corpus; not a real service">
<meta name="generator" content="dark-sentinel-lab/1.0">
<title>{html.escape(title)}</title>
</head>
<body>
<div id="lab-banner" style="background:#7a1f1f;color:#fff;padding:10px;font-family:sans-serif">
<strong>{html.escape(BANNER)}</strong>
</div>
<!-- build 2024.11 staging -->
<!-- TODO: remove cdn reference before launch -->
<link rel="stylesheet" href="https://cdn-static-eu.hostvault.net/assets/app.css">
{body}
</body>
</html>
""".encode("utf-8")


def render_index(corpus: Corpus, source: dict) -> bytes:
    members = corpus.for_source(source["name"])
    kind = "vendor" if source["kind"] == "market" else "user"
    rows = "\n".join(
        f'<li><a href="/{kind}/{html.escape(p["handle"])}">{html.escape(p["handle"])}</a>'
        f' — {html.escape(p.get("category") or "")}</li>'
        for p in members
    )
    return page(source["name"], f"<h1>{html.escape(source['name'])}</h1>\n<ul>\n{rows}\n</ul>")


def render_profile(corpus: Corpus, persona: dict) -> bytes:
    source = corpus.sources[persona["source"]]
    kind = "vendor" if source["kind"] == "market" else "user"
    parts = [
        f'<h1 data-f="handle">{html.escape(persona["handle"])}</h1>',
        f'<div data-f="category">{html.escape(persona.get("category") or "")}</div>',
        f'<div data-f="trust_score">{html.escape(str(persona.get("trust_score") or ""))}</div>',
        f'<div data-f="first_seen">{html.escape(persona.get("first_seen") or "")}</div>',
        f'<div data-f="last_seen">{html.escape(persona.get("last_seen") or "")}</div>',
        f("bio", persona.get("bio")),
    ]
    # The only multi-line text in the corpus. <pre> keeps the newlines, and the
    # newlines are load-bearing: extract/pgp.py checks the armour's crc24.
    for block in corpus.key_blocks.get(persona["id"], []):
        parts.append(f'<pre data-f="key_block">{html.escape(block)}</pre>')

    for post in corpus.posts.get(persona["id"], []):
        parts.append(
            '<article data-f="post">'
            + f("title", post.get("title"), "h2")
            + f("posted_at", post.get("posted_at"))
            + f("category", post.get("category"))
            + f("body", post.get("body"), "p")
            + "</article>"
        )

    if source["kind"] == "market":
        parts.append(
            f'<a data-f="feedback_link" href="/{kind}/'
            f'{html.escape(persona["handle"])}/feedback">buyer feedback</a>'
        )
    return page(f'{persona["handle"]} — {persona["source"]}', "\n".join(parts))


def render_feedback(corpus: Corpus, persona: dict) -> bytes:
    rows = corpus.feedback.get(persona["id"], [])
    body = [f'<h1>feedback for <span data-f="handle">{html.escape(persona["handle"])}</span></h1>']
    for row in rows:
        body.append(
            '<article data-f="feedback">'
            + f('buyer_handle', row["buyer_handle"], "span")
            + f('rating', str(row["rating"]), "span")
            + f('posted_at', row.get("posted_at"), "span")
            + f('body', row.get("body"), "p")
            + "</article>"
        )
    if not rows:
        body.append("<p>no feedback yet</p>")
    return page(f'feedback — {persona["handle"]}', "\n".join(body))


SERVER_STATUS = b"""<!DOCTYPE html><html><head><title>Apache Status</title></head><body>
<h1>Apache Server Status for lab</h1>
<!-- PLANTED MISCONFIGURATION. A real /server-status leaks vhosts, client
     addresses and in-flight request URIs. recon/fingerprint.py flags it. -->
<dl><dt>Server Version: Apache/2.4.41 (Ubuntu)</dt>
<dt>Server Built: 2024-11-02</dt>
<dt>Current Time: runtime</dt>
<dt>Parent Server Generation: 1</dt></dl>
<table><tr><th>Srv</th><th>PID</th><th>Acc</th><th>M</th><th>VHost</th><th>Request</th></tr>
<tr><td>0-0</td><td>2141</td><td>0/12/12</td><td>_</td>
<td>lab.internal:80</td><td>GET /vendor/Dr3adPirat3 HTTP/1.1</td></tr>
<tr><td>1-0</td><td>2142</td><td>0/9/9</td><td>W</td>
<td>lab.internal:80</td><td>GET /server-status HTTP/1.1</td></tr></table>
<p>LAB TARGET - synthetic. Not a real server.</p>
</body></html>
"""

ROBOTS = (
    "# LAB TARGET - synthetic corpus for collector testing, not a real service.\n"
    "User-agent: *\n"
    "Disallow: /admin\n"
    "Disallow: /backup\n"
)


# ─────────────────────────────────────────────────────────────────────────────
# Server
# ─────────────────────────────────────────────────────────────────────────────

class Handler(BaseHTTPRequestHandler):
    server_version = "nginx/1.18.0"
    sys_version = ""
    corpus: Corpus = None  # type: ignore[assignment]

    def log_message(self, fmt: str, *args) -> None:
        sys.stderr.write(f"  lab {self.address_string()} {fmt % args}\n")

    def _send(self, code: int, body: bytes, content_type: str = "text/html; charset=utf-8"):
        self.send_response(code)
        self.send_header("Content-Type", content_type)
        self.send_header("Content-Length", str(len(body)))
        # Header order is itself a weak fingerprint; recon/correlate.py compares
        # it, so it is emitted deliberately and consistently.
        self.send_header("X-Powered-By", "PHP/7.4.33")
        self.send_header("ETag", 'W/"5f2a1c-1b4e"')
        self.send_header("X-Lab-Target", "synthetic; not a real service")
        self.end_headers()
        if self.command != "HEAD":
            self.wfile.write(body)

    def do_HEAD(self) -> None:
        self.do_GET()

    def do_GET(self) -> None:  # noqa: N802
        path = self.path.split("?", 1)[0].rstrip("/") or "/"
        corpus = self.corpus

        if path == "/":
            source = corpus.sources["market_alpha"]
            return self._send(200, render_index(corpus, source))
        if path == "/robots.txt":
            return self._send(200, ROBOTS.encode(), "text/plain; charset=utf-8")
        if path == "/server-status":
            return self._send(200, SERVER_STATUS)
        if path == "/favicon.ico":
            # 1x1 PNG. recon hashes it with mmh3 over its base64, Shodan-style.
            import base64  # noqa: PLC0415
            png = base64.b64decode(
                "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mP8"
                "z8BQDwAEhQGAhKmMIQAAAABJRU5ErkJggg=="
            )
            return self._send(200, png, "image/png")
        if path in ("/sitemap.xml", "/server-info"):
            return self._send(404, b"not found")

        parts = [p for p in path.split("/") if p]
        if len(parts) >= 2 and parts[0] in ("vendor", "user"):
            persona = corpus.by_handle.get(parts[1])
            if persona is None:
                return self._send(404, page("not found", "<p>no such profile</p>"))
            if len(parts) == 3 and parts[2] == "feedback":
                return self._send(200, render_feedback(corpus, persona))
            return self._send(200, render_profile(corpus, persona))

        if len(parts) == 1 and parts[0] in corpus.sources:
            return self._send(200, render_index(corpus, corpus.sources[parts[0]]))

        return self._send(404, page("not found", "<p>no such page</p>"))


def make_cert(directory: Path) -> tuple[Path, Path]:
    """Self-signed cert whose SAN and serial already exist in clearnet_obs.

    Not a security control and not pretending to be one: a hidden service
    already authenticates by its onion address. This exists so recon has a
    certificate to read and correlate — see the module docstring.
    """
    from cryptography import x509  # noqa: PLC0415
    from cryptography.hazmat.primitives import hashes, serialization  # noqa: PLC0415
    from cryptography.hazmat.primitives.asymmetric import rsa  # noqa: PLC0415
    from cryptography.x509.oid import NameOID  # noqa: PLC0415

    directory.mkdir(parents=True, exist_ok=True)
    cert_path, key_path = directory / "lab.crt", directory / "lab.key"
    if cert_path.exists() and key_path.exists():
        return cert_path, key_path

    key = rsa.generate_private_key(public_exponent=65537, key_size=2048)
    name = x509.Name([
        x509.NameAttribute(NameOID.COMMON_NAME, TLS_SAN),
        x509.NameAttribute(NameOID.ORGANIZATION_NAME, "Dark Sentinel lab target"),
    ])
    now = datetime.now(timezone.utc)
    cert = (
        x509.CertificateBuilder()
        .subject_name(name)
        .issuer_name(x509.Name([
            x509.NameAttribute(NameOID.COUNTRY_NAME, "US"),
            x509.NameAttribute(NameOID.ORGANIZATION_NAME, "Let's Encrypt"),
            x509.NameAttribute(NameOID.COMMON_NAME, "R3"),
        ]))
        .public_key(key.public_key())
        .serial_number(TLS_SERIAL)
        .not_valid_before(now - timedelta(days=1))
        .not_valid_after(now + timedelta(days=3650))
        .add_extension(
            x509.SubjectAlternativeName([
                x509.DNSName(TLS_SAN),
                x509.DNSName(f"www.{TLS_SAN}"),
            ]),
            critical=False,
        )
        .sign(key, hashes.SHA256())
    )
    cert_path.write_bytes(cert.public_bytes(serialization.Encoding.PEM))
    key_path.write_bytes(key.private_bytes(
        encoding=serialization.Encoding.PEM,
        format=serialization.PrivateFormat.TraditionalOpenSSL,
        encryption_algorithm=serialization.NoEncryption(),
    ))
    return cert_path, key_path


def serve(port: int, corpus: Corpus, tls: Optional[tuple[Path, Path]] = None) -> None:
    Handler.corpus = corpus
    httpd = ThreadingHTTPServer(("0.0.0.0", port), Handler)
    if tls:
        import ssl  # noqa: PLC0415

        context = ssl.SSLContext(ssl.PROTOCOL_TLS_SERVER)
        context.load_cert_chain(certfile=str(tls[0]), keyfile=str(tls[1]))
        httpd.socket = context.wrap_socket(httpd.socket, server_side=True)
    scheme = "https" if tls else "http"
    print(f"  lab listening {scheme}://0.0.0.0:{port}", flush=True)
    httpd.serve_forever()


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description="Serve the lab target.")
    parser.add_argument("--http", type=int, default=8080)
    parser.add_argument("--https", type=int, default=8443)
    parser.add_argument("--certs", type=Path, default=Path("/certs"))
    parser.add_argument("--no-tls", action="store_true")
    args = parser.parse_args(argv)

    corpus = Corpus()
    print(f"  lab corpus: {len(corpus.personas)} personas, "
          f"{sum(len(v) for v in corpus.posts.values())} posts, "
          f"{sum(len(v) for v in corpus.feedback.values())} feedback rows", flush=True)
    print(f"  {BANNER}", flush=True)

    if not args.no_tls:
        tls = make_cert(args.certs)
        threading.Thread(target=serve, args=(args.https, corpus, tls), daemon=True).start()
    serve(args.http, corpus)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
